### ISSUE TITLE
Keeps asking for folder access in macOS even though the .app and binary have Full Disk Access

### ISSUE THREAD

**Issue by intrepidsilence** [BlitterStudio/amiberry#1034]
**Description:**
in macOS Ventura (perhaps other versions) on M1Max, freshly compile (provided binary on GH will not run currently), even if the .app and the Amiberry binary inside it have been given Full Disk Access, it continues to ask for permission for every file it opens, so it asks somewhere between 3x and 12x depending on what you are doing.

**To reproduce:**
1. Add Amiberry.app and Amiberry to Full Disk Access in settings
2. Run Amiberry
3. Get asked a ton of permission questions every time you do anything like opening files, saving configs, starting emu, stopping emu

**Expected behavior**
App should run without asking for permission to folders when it has Full Disk Access

**Desktop (please complete the following information):**

- OS: macOS Ventura 13.0.1

- Version: Amiberry 5.4 plus commits as of Dec 7, 11am EDT from GitHub 

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment]
I'm afraid I don't have the hardware to test or help with this issue.

The MacOS builds are supplied by other generous members of the community, but without the hardware to run tests or debug it here, there's not much I can do from my side.

Perhaps if someone else is willing to jump in and assist with this, we can figure out why it happens and how it could be fixeed...

**Comment by erikbernsen** [comment]
I have a Mac and see the same problem. I don't know much about development about Mac, but what I found out is that if you copy the Amiberry.app to /Applications the permissions work as expected. Furthermore, if you don't want to do so, starting the executable directly from Amiberry.app/Contents/MacOS/Amiberry also work without asking permissions. In UI you can do it by right clicking from Finder on Amiberry.app, select Show Package Contents. Navigate to Contents/MacOS and double click Amiberry. Hope that helps. For me having these solutions is good enough.

**Comment by intrepidsilence** [comment]
I had already copied it to /Applications and it did not fix it. And I disagree that running it manually is a fix that is good enough. Other applications that are not signed by Apple do not have these issues and it is worth fixing.

**Comment by erikbernsen** [comment]
Strange that copying to /Applications didn’t fix it for you but did for me. I can understand manually starting executable instead of opening the Amiberry.app wouldn’t be a good solution for most, but for me it works as I wrote a launcher from which I start different games. Unfortunately I have very little knowledge on this topic so difficult to help further.

**Comment by BluewizardNet** [comment]
I had this problem myself with 5.5b and was experimenting today.

It seems that the Info.plist does not like the version 5.5b as it puts the 5b in as the Integer IFMinorVersion and since 5b isn't an integer the Info.plist fails validation and it seems to mess up the signing after that.

I made a local tweak to src/osdep/target.h

I changed line 27 to be:
  #define AMIBERRYVERSION _T("Amiberry v5.5 (2022-12-13)")
Dropping the b.

Once I rebuilt it asked me for permission once and now things work without being prompted all the time.  MUCH better.

I am using MacOS 13.1 on a 14 inch MBP with M1 Pro chip.

I hope this works for someone else as well.

**Comment by midwan** [comment]
Interesting, thanks for that.
Is the version string is the problem, then this won't be an issue with the next release since it will be changed to "5.5"

**Comment by BluewizardNet** [comment]
It does look like the version string is the problem with how things currently are.

The Info.plist wants the major and minor versions as an integer.

Since the make-bundle.sh parses the version string in the src/osdep/target.h and then uses that parsed version to populate the Info.plist that causes a problem currently.

3 options I see.  
* The first don't have non numeric values for the version numbers in the version string. 
* Update the make-build.sh to remove any non-numerics from the version string prior to populating the the Info.plist
* If you want additional release numbers add another . release like 5.5.1 or 5.5.2 but that will require modifying the make-bundle.sh script as well.  

I am happy to do I change to the make-bundle.sh to "protect" against non-numerics in the make-bundle.sh as it looks like a simple parsing to remove non [0-9] characters from those fields would do it.  That said I have not dug a ton into it but that what it seems.

**Comment by midwan** [comment]
This should be resolved now, with the v5.5 release. 
The Intel binary is already there, the M1 one will follow soon (once it's provided by @solskogen who kindly compiles it for me).
