### ISSUE TITLE
Amiberry 5.4 DietPi (v8.12) and no sound enabled.

### ISSUE THREAD

**Issue by FabrizioRadica** [BlitterStudio/amiberry#1043]
Hi, i show you a video with the problem.
Amiberry 5.4 starts fine but seems not enabling the audio on default.uae

Test:
- Starts Amiberry
- Open Amiberry GUI
- Enalbe Audio (if not enabled)
- Back on Amiga.. then back again on Amiberry GUI...
- Sound still disabled. 

https://user-images.githubusercontent.com/1652242/209563631-91870edc-e340-4d6c-828d-31e78bfa4d5d.mp4

Even if I edit default.uae by hand, it still won't mute.

**Comment by midwan** [comment]
Looks like no audio device was detected by SDL2, and that's why:
- You don't see any audio devices listed above, the dropdown is empty/disabled
- Sound emulation/output is disabled automatically once you resume emulation, since there's nothing that SDL2 can use to output the sound from.

This is certainly not the normal situation, since by default the RPI outputs sound through the HDMI port (unless you modify that behavior, e.g. by editing `/boot/config.txt`).

If you have any external (e.g. USB) sound devices, those would also work and be listed there. Having nothing available seems like a problem outside the scope of Amiberry itself, and more of a system issue. :-/

**Comment by FabrizioRadica** [comment]
Hi, now works fine.
I've Update Dietpi to v8.12 and now... works.
You can close this thread for me.
Tnx :)
