### ISSUE TITLE
Drawbridge support for macOS

### ISSUE THREAD

**Issue by n0rt0nthec4t** [BlitterStudio/amiberry#1063]
It appears Drawbridge support support is not implemented in macOS builds.. Is this something that can be added in?

**Comment by midwan** [comment]
@n0rt0nthec4t It's not excluded from the build, so it should work the same way as it does under Linux.
But I'm not sure if there are differences in the permissions and device handling under macOS, as I don't have one to test with here... :-/

**Comment by midwan** [comment]
@n0rt0nthec4t 
You'll have to change the floppy type to one of the FB: options first, to enable it (FB stands for Floppy Bridge).
Check the wiki also: https://github.com/BlitterStudio/amiberry/wiki/GUI:-Floppy

**Comment by midwan** [comment]
@n0rt0nthec4t 
That's an indication that one of these things is happening:
- the device is not connected
- the serial port could not be opened (e.g. due to permissions)
- the serial port is named differently, so it couldn't be found (e.g. due to macOS differences)

On Linux, usually the device name is something like `/dev/ttyUSB0` (or a higher USB device id, depending on how many you have available). Can you see if that's available when your device is connected? If it's there, then perhaps you need to give your username permissions to access it. On Linux, usually that's done by becoming a member of the `uucp` group, for example.

I'm not sure if the above is different under macOS, but the same principal should apply there as well. :)

**Comment by n0rt0nthec4t** [comment]
Yes, seems teh USB serial UARTs are assigned different names. Ie. I have
crw-rw-rw-  1 root  wheel   0x9000004 21 Mar 07:25 /dev/tty.usbserial-A502IP0V
crw--w----  1 mark  tty    0x10000000 21 Mar 07:18 /dev/ttys000
crw--w----  1 mark  tty    0x10000001 21 Mar 07:18 /dev/ttys001
crw--w----  1 mark  tty    0x10000002 21 Mar 07:41 /dev/ttys002
crw--w----  1 mark  tty    0x10000003 21 Mar 07:18 /dev/ttys003
crw--w----  1 mark  tty    0x10000004 21 Mar 07:18 /dev/ttys004

**Comment by n0rt0nthec4t** [comment]
@midwan thanks.. If you and/or Rob need assistance in testing, reach out

**Comment by midwan** [comment]
@n0rt0nthec4t 
Please test after the latest commits which should fix this

**Comment by n0rt0nthec4t** [comment]
No worries.. will test when teh next binary builds are up. Also, noticed with 5.6 there is no binary build for Apple M1, just X86 only?
