### ISSUE TITLE
Query: GUI -> Paths -> helptext 

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1155]
![example](https://imgur.com/vpObmpT.png)

I believe the 'Beware' warning about any changes to the contents of  conf/gamecontrollerdb.txt the user makes being lost, equally applies to the XML file ( whdboot/game-data/whdload_db.xml)

The simple case for where the user ends up modifying the XML file, comes in the form of many newer/recent Amiga game titles, which are distributed in multiple formats, one of which being a whdload.lha archive, which may instantly appeal to users of THEA500 Mini, and typically there comes instructions of how to add the XML snippet to the existing whdload_db.xml file. (obviously users may modify the XML to suit their own setup whatever as well, but non-savvy users may get caught out here)

First, I'm just questioning the intent of the wording, wrt to my reviewing of existing helptext code.

Second, might it be an idea, for both update widgets to move the existing files (to filename.bak or .orig), before downloading/replacing said files? It'd give the user a chance to recover any edits, in the case where they use the update widgets 'without thinking' ;)

Either way, I just needed to sure the position here, before editing this helptext area.

TIA

**Comment by midwan** [comment]
I've added some code that will optionally take a backup of the existing file, before it's replaced with the newer version.

Neither of these two files are normally modified by the users:
- The XML file should be updated by requesting/sending a new snippet to the official repo, where the file gets updated from. That way, everyone can benefit from new updates.
- The controllerdb file is the official one coming from the SDL2 repo. There is a separate one for user modifications, under `controllers`, which can be modified and will not be affected by any updates.

Regardless, since many people might end up modifying these files anyway, a word of warning is the least I could do. Well, now we can also take a backup :)

Note: this is not merged in `master` yet, as I need to test it more thoroughly. Currently only in the `preview` branch.

**Comment by giantclambake** [comment]
Copy that ~ I wasn't terribly worried about user edits to these files until I saw the above scenario playing out IRL with newly released titles, and realized the threat was real =) You're right -- in a perfect world, authors of these newer titles should submit their XML snippets to Horace for inclusion in the XML, then the install instructions would be "ensure you update the whdload XML file on the Paths panel" .....alas, it's planet Earth and ppl aren't perfect  ;)

All good ~ I'll checkout the preview branch in due course, thanks!

**Comment by giantclambake** [comment]
Seems to work 'as expected' caveat the following ;

 - preview branch -> Makefile -> extraneous 'else' at line: 102

**else** ifeq ($(PLATFORM),$(filter $(PLATFORM),rpi1-sdl2 rpi2-sdl2 rpi3-sdl2 rpi4-sdl2 rpi5-sdl2))

Should be; ifeq ($(PLATFORM),$(filter $(PLATFORM),rpi1-sdl2 rpi2-sdl2 rpi3-sdl2 rpi4-sdl2 rpi5-sdl2))

After using the 2 update widgets;

This seems ok.....

gcb@gallah:~/preview/amiberry$ ls -l conf
total 1004
-rw-r--r-- 1 gcb gcb   2383 Nov 12 11:05 amiberry.conf
-rw-r--r-- 1 gcb gcb   1578 Nov 12 10:34 amiberry-osx.conf
-rw-r--r-- 1 gcb gcb     45 Nov 12 10:34 dir.txt
-rw-r--r-- 1 gcb gcb 488355 Nov 12 10:34 gamecontrollerdb.bak
-rw-r--r-- 1 gcb gcb 523692 Nov 12 11:05 gamecontrollerdb.txt

However, I question the permissions we're left with here on 'whdload_db.bak' ...

gcb@gallah:~/preview/amiberry$ ls -l whdboot/game-data
total 15464
-rwxr-xr-x 1 gcb gcb 7809675 Nov 12 10:34 whdload_db.bak
-rw-r--r-- 1 gcb gcb 8022509 Nov 12 11:03 whdload_db.xml

TIA

**Comment by midwan** [comment]
Thanks, I missed that in the Makefile after the cleanup. Fixed now.
The permissions are probably not a problem, the existing file is just renamed, while the new one is downloaded from the Github repo directly. It's possible they will differ.
