### ISSUE TITLE
[rink a dink redux] imperfect A500 emulation

### ISSUE THREAD

**Issue by lvd2** [BlitterStudio/amiberry#1211]
**Describe the bug**
In a "Rink a Dink: REDUX" demo from [here](https://www.pouet.net/prod.php?which=61182), imperfect emulation is observed.

**To Reproduce**

1. build d1daf8656e0dafee7f94530771f3dc8059eb9d3c for x86-64

2. Download .ADF from the page above (md5sum = 06c32641851aae45fdfa2ce8af1d10c9)

3. Run amiberry via quickstart as A500. The first glenz vector effect will have glitches:
![Screenshot at 2023-12-25 22-55-58](https://github.com/BlitterStudio/amiberry/assets/6805375/1351f698-e7a2-4f89-84d3-bf66f88891e2)

4. Stop emulation, change config setting by ticking CPU Speed -> Cycle exact. Now glenz is OK, but instead the first plasma is glitching:
![Screenshot at 2023-12-25 22-57-24](https://github.com/BlitterStudio/amiberry/assets/6805375/11e98a7d-2e92-4899-b1e8-8a420e832811)

**Expected behavior**
No glitches in both effects

**Desktop (please complete the following information):**
ubuntu 22.04 in linux mint MATE flavour

**Comment by midwan** [comment]
@lvd2 
Thanks for taking the time to report this.
It's true that the `master` branch version does not have 100% perfect emulation, due to optimizations done to keep the performance at acceptable levels for slower devices. However, there is a newer version in the `preview` branch, which I believe you'll find is much more accurate (it's currently in-sync with the latest WinUAE sources).

The reason it's still in a separate branch and not merged into `master` yet, is that it's much more demanding in resources. About x2-x3 times more, which makes it unusable on anything below an RPI4 (and even there, it will struggle in some cases). 

However, for x86_64 is actually the preferred choice, since you don't have an issue with CPU power there. The latest version also includes JIT support for x86_64, so there's not much reason to use the version from `master` on that platform.

Give it a try and you'll find that the demo works perfectly there, with the default A500 settings (which include Cycle-accurate emulation).

**Comment by lvd2** [comment]
Thanks for your response! 'preview' branch works like a miracle :)
