### ISSUE TITLE
Graphic issue with Trolls_AGA and Start Problem with Trolls

### ISSUE THREAD

**Issue by NoobieMaks** [BlitterStudio/amiberry#1279]
1. Graphic issue with "Trolls_v1.2_AGA_0996.lha": All platforms disappear when the character is moved to the upper area of the levels!

This happens in my current build (buster + RePi 4.8.6 + Amiberry 5.6.8), in my older build (stretch + RePi 4.5.11 + Amiberry 3.0.11) this does not happen.

Start the game -> move into the first door (TOYLAND AREA 1)  -> Jump on the first platform above you -> jump on the second platform -> jump on the airplane and time it clever so you can jump further to the third platform on the right (a lovely bear is sitting on it) -> and then only jump up and you will see that all platforms are disappearing when you entering a certain height, when you fall down on the platform everything comes back into the picture. -> This can be recreated in every other level too.

I found no setting in the GUI to fix it.

2. Searching for a working alternative for Trolls I ran into the start problem of "Trolls_v1.2":
Amiga DOS Error: "Exception "Illegal Instruction" ($E010) at $23958E (Slave $16E) occured.
In my older build I did not have this problem.

I found out when I create a config-file and set the CPU from 68000 to 68020 the game runs.
No graphic issue in this version.

The third alternative of Trolls ("Trolls_v1.3_CD32.lha")  is running promptly and does also not have the graphic issue.

**Comment by midwan** [comment]
Regarding `Trolls_v1.2_AGA_0996.lha`, I can recreate the issue in both `master` and `preview`. The Preview version is in-sync with the latest WinUAE, so I suspect this is an upstream bug there as well, but I didn't have a chance to test it.

The issue with `Trolls_v1.2` seems to be in the package itself: it requires an 020 CPU, when it shouldn't. This is fixable by changing the requirements in the XML of course - @HoraceAndTheSpider

**Comment by giantclambake** [comment]
Seeing as it's been some time since this was checked, decided to test the above scenarios (+1) using `Preview`/x86-64, to see if any changes between then and the now (nearly 6months), has made any difference here.

`./amiberry Trolls_v1.2.lha`  -- > As per above results, crashes ; requires CPU=68020 to work ; it shouldn't (OCS/ECS title)

`./amiberry Trolls_v1.3_CD32.lha` --> works as expected, top levels playable/visible

`./amiberry cdroms/trolls/"Trolls (1993)(Flair Software)(PAL)[!].cue"`  --> works as expected, top levels playable/visible

`./amiberry Trolls_v1.2_AGA_0996.lha` --> ...WHDLoad splash screen corrupted...(textbox background)...

![ex](https://imgur.com/VRSfxuF.png)

...intro sequence runs, displaying various bad graphics artifacts on each cut-scene and during the pages of credits. Game loader splash screen is correct....gameplay is correct, until reaching upper levels which visibly disappear. From start-up through into gameplay, music replay is uninterrupted, and sfx in-game always heard. Quit amiberry...this result tallies.

Test 2: Object of the test, is to sanity check the whdbooter environment,  by using a real AmigaOS install instance instead.

`./amiberry conf/ClassicWB-P96.uae`    //<-- I hope that is self-explanatory enough ;)

Extract the same Trolls_v1.2_AGA_0996.lha file to ..ie; DH3:, open the resultant drawer, double-click on the game icon...

...intro sequence runs, there are **_no_** graphical artifacts/glitches during intro sequence ...instead, music playback gets interrupted at that same moment graphical glitches would've occurred in amiberry direct-load. Gameplay is correct, however music replay (I think it's using PT based mod) is still being interrupted, and sfx related to pick-ups do not always trigger, and are often not heard ...and again, towards the top of the Toyland level, the platform(s) disappear. At some points when you trigger a sfx replay, the end of the sample 'hangs' and becomes repetitive 'chirping'.  Quit amiberry.

Next...head over to the mantis bug-tracker for this title, to check if there's any tickets listed... I think there's 3 related to the disappearing upper level, all from UAE users...of more interest to me, is those few reports allegedly using real Amiga A600 hw, getting what they describe as a 'squeaking' noise.....

...'chirping' is very close to 'squeaking' in effect, and if I can replicate that, using amiberry/ClassicWB, similar to what's happening on real Amiga hw (and AmigaOS instance), _that_ result tends to suggest the Trolls_v1.2_AGA_0996.lha archive is to blame here...seeing as the amiberry emulation mimics the A600 situation with the same whdload.lha file.

I don't think there's an amiberry related bug here (nor upstream in WinUAE).....my conclusions;

*`Trolls_v1.2.lha` has a problem (but runs fine with CPU=68020) -- this is fodder for @HoraceAndTheSpider 

*`Trolls_v1.2_AGA_0996.lha` has a bigger problem -- this is fodder for the mantis bug-tracker

HTH
