### ISSUE TITLE
Builds above 5.6.8 (downloaded or self-compiled) quit unexpectedly on M3 chip and macOS 14.5

### ISSUE THREAD

**Issue by StusBrainDump** [BlitterStudio/amiberry#1335]
**Describe the bug**
As title - Builds above 5.6.8 (downloaded or self-compiled) quit unexpectedly on M3 chip and macOS 14.5

**To Reproduce**
Download an "m1" build above 5.6.8, including preview builds, and it will display the dialog "Amiberry.app quit unexpectedly."
Downloading the m1 build of 5.6.8 and running it is successful with no errors.

![image](https://github.com/BlitterStudio/amiberry/assets/119980446/ba84b118-afd6-4417-bef8-e054769c033f)

**Comment by midwan** [comment]
I don't have the hardware to test an Apple Silicon build here, I'm afraid. But here are a few ideas:
- Try renaming the /Documents/Amiberry folder, and let it be recreated by running the app again. It will be populated with the defaults, so you can move your stuff back in there, if that works.
- Try the Preview version. On faster platforms than the RPI4, that's the better version anyway. There are pre-compiled versions in the Releases (tagged as Pre-release) or  you can also build it yourself, of course (just switch to the `preview` branch).

Beyond that, I'm not sure what might be wrong, perhaps someone else with access to the hardware might be able to help further...

**Comment by StusBrainDump** [comment]
Hi

- Already tried clearing the /Documents/Amiberry folder but still fails

- As mentioned above, I've tried the preview build (6.3.0, either pre-compiled or compiled myself) and it has the same problem, quits unexpectedly.

**Comment by midwan** [comment]
@solskogen maybe you can give this a try and see if you can recreate it?
The intel build seems to work fine here, on an old Mac-mini running macOS 14.

**Comment by solskogen** [comment]
I'm seeing the same thing on my M1.

**Comment by midwan** [comment]
@StusBrainDump maybe you could try a `git bisect` (https://git-scm.com/docs/git-bisect) to see which commit broke things?
I cannot really test this here, unfortunately.

From what you mentioned so far: 
- It happens after 5.6.8 (so, that's the last known "good" commit)
- It only affects Apple Silicon builds (the intel ones seem to work fine) 
- It still builds fine (otherwise my build pipelines would have caught it)
- It happens for both pre-compiled binaries and self-compiled ones (which probably excludes an error in the CI pipeline)

If we can narrow down what change started triggering this, we could probably find a fix.

**Comment by StusBrainDump** [comment]
Your points are accurate. I'm going to be going on holiday for a week from tomorrow so it may have to wait for now. Will get on it as soon as I can after :)

**Comment by solskogen** [comment]
I reinstalled my macOS today on my M1 and now, Amiberry just works. 
Perhaps something happened during Xcode upgrade or something like that? Perhaps try to uninstall and install it.

**Comment by solskogen** [comment]
Could you also try to reinstall homebrew?

**Comment by StusBrainDump** [comment]
OK I've successfully reinstalled the dependencies via homebrew as listed on https://github.com/BlitterStudio/amiberry/wiki/Compiling-for-macOS.

However anything above 568 still doesn't work, including the latest 572.

**Comment by solskogen** [comment]
Try Amiberry-preview ([6.3.2](https://github.com/BlitterStudio/amiberry/releases/tag/preview-v6.3.2))

**Comment by StusBrainDump** [comment]
6.3.2 Fails

HOWEVER ... I've done my own testing of downloading and compiling various commits and have found the following:

amiberry-ee4131061894a30d96e6eaa5976aac13a92376ce - WORKS
amiberry-57a76edebb0cf29c284971815c012dd7aa3730a0 - FAILED TO COMPILE
amiberry-797c2a835120a7cf0300951f885653df961fba7c - FAILED TO COMPILE
amiberry-a8d5ed6723391b498eddcb3e90da4c3cc13b26f7 - FAILED TO COMPILE
amiberry-fedad262f37a5576931c523e48489d6aba81c756 - FAILED TO RUN (Quit Unexpectedly)
amiberry-cfa9cb0bf517c5013fb14615736d5c866adbc81a - FAILED TO RUN (Quit Unexpectedly)

So from this testing, it appears that amiberry-ee4131061894a30d96e6eaa5976aac13a92376ce was the last commit to compile and run successfully in my setup. Subsequent commits forward in time either failed to compile or produced the "Quit Unexpectedly" error.

Hope that helps somewhere :)

**Comment by StusBrainDump** [comment]
![image](https://github.com/BlitterStudio/amiberry/assets/119980446/c8e67245-7925-486a-a921-ab577b448aa9)

**Comment by midwan** [comment]
It looks like the breaking started after the refactoring to use `std::string` instead of `char*` in various places. The WHDBooter code had some references that didn't get updated, so builds failed until that commit (2 commits later). Perhaps there's something I missed, but it doesn't seem to have any issues anywhere else, which is puzzling. 

Does it also fail if you skip the GUI? Many of the changes were in the GUI panels, perhaps we can narrow it down if you can test without the GUI (from the command line, that's using the `-G` option).

**Comment by StusBrainDump** [comment]
OK, yes that file was missing. Very very odd that previous versions appear to work without it. Now I have that file, 572 works.

**Comment by midwan** [comment]
That's very odd indeed, considering it's always been part of the distribution, and there's a startup script that copies all relevant files in the Users folder.

Perhaps it was an issue with pre-existing data there, which didn't get overwritten. In other words, perhaps if you renamed the `/Users/blah/Documents/Amiberry` folder, and let Amiberry recreate it on startup, it would have worked.

In any case, glad to see it works now!
