### ISSUE TITLE
Linux x86_64 crashes when saving config

### ISSUE THREAD

**Issue by jman-schief** [BlitterStudio/amiberry#1345]
**Describe the bug**
Amiberry crashes when saving the configuration

**To Reproduce**

1. Download and unzip the x86_64 release 5.7.1

2. Launch binary

3. Insert a name and a description of a configuration (example "test" and " this is a test"), click to save

4. Amiberry segfaults, creates a zero-size file "test.uae"

**Expected behavior**
I think I should be able to save a config at any time, even without a description, right?

**Desktop (please complete the following information):**

- OS: Debian Trixie x86_64

- Version 5.7.1

**Comment by midwan** [comment]
That seems like a nasty bug that got through, thanks. I'll get it fixed and probably release an updated binary.
In the meantime, since you're on x86_64, you really _should_ be using the 6.x version instead. :)

**Comment by FreeMEM** [comment]
Opened #2036 with a fix.

Root cause: `cfgfile_save()` opens the destination `.uae` with `fopen("w")`, which commits a 0-byte truncate to the filesystem journal immediately while the data write only reaches disk on the next kernel writeback (~5 s default on ext4). If Amiberry exits or the host is killed in that window, the file is left at 0 bytes — and because `cfgfile_load_2`/`target_fixup_options` does not handle a zero-length config gracefully, the next launch segfaults, locking out wrappers that auto-load with `--config`.

The PR switches the AMIBERRY branch to a write-tmp + `fsync` + `rename(2)` pattern with directory `fsync` after, so the final path is always either the previous content or the new content, never empty. The non-AMIBERRY branch is untouched.

Reproduced and validated on Linux/Wayland with both 7.1.1 and 8.1.5; full reproducer + risk assessment in the PR description.
