### ISSUE TITLE
Question: Is the GUI->WHDLoad panel -> Slave Data path: textbox field just a 'telltale' or a config tool?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1347]
If the XML snippet for the selected whdload.lha file loaded contains `<datapath>data</datapath>`, then this is reflected in the WHDLoad panel like so (and you likely don't need to change anything);

![ex](https://imgur.com/4BtBQL1.png)

However, and as exampled by #958 there are numerous whdload.lha files, for which the XML contains `<datapath />`, and when such a file is loaded you see (note: such titles do NOT start&run) ;

![ex2](https://imgur.com/jWUKz9b.png)

If this is a config tool, I'm expecting to be able to enter `data` into the (vacant) textbox, and then go Start, and amiberry would append `DATA=data` to `/tmp/amiberry/s/startup-sequence` ...which effectively gets these titles working as expected.

I do realize this should be fixed in the XML or via mantis (see HoraceAndTheSpider/Amiberry-XML-Builder/issues/121), but also gives rise to my quandary...

ie; is this a (as yet unimplemented?) config tool to enable users to work-around such issues, or is it merely a 'telltale' to inform users what the associated XML snippet contains?

TIA

**Comment by midwan** [comment]
Most of the fields in this window are read-only, by design.
The Custom fields can be changed, and the "custom" option can be specified, but the rest come from the XML contents. The window is meant to visualize what we got back for the specific title.
An exception is the Slave option, where you can choose another (if the game has more than one).

**Comment by giantclambake** [comment]
Thanks for the clarification ;)
