### ISSUE TITLE
abort() when amiberry has not been installed at least once

### ISSUE THREAD

**Issue by m0ppers** [BlitterStudio/amiberry#1429]
**Describe the bug**
SDLTrueTypeFont::SDLTrueTypeFont. Couldn't open /usr/share/amiberry/data/AmigaTopaz.ttf: No such file or directory
Internal error; file src/osdep/gui/main_window.cpp, line 1050

Aborted (core dumped)

**To Reproduce**
I never installed amiberry and wanted to compile it from source and execute it from the source directory after the build. However there seem to be some hardcoded things which make it abort().

**Expected behavior**
For development I want to be able to run it standalone from my source directory without having to install it.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Arch

- Version 

**Additional context**
not sure if this is supposed to work. I guess it would be nice? simple workaround was to install it once from AUR and then I could execute ./amiberry from my source directory.

super minor as the fix is trivial. feel free to ignore it and close it right away

**Comment by m0ppers** [comment]
ah. not sure if this is an important info: I am working in the preview branch

**Comment by midwan** [comment]
This seems like a bug I created recently. It should absolutely be possible to run it from the build directory, as that was something which was always possible.

I think when I added the extra paths it looks for, is probably when this started happening. You mentioned you're using Arch, so I'm guessing that `XDG_DATA_DIR` is set. I'll take a look there, it should check if that directory exists, before using it. The fallback is still the directory it starts from, but only if all the other search paths have failed.

**Comment by midwan** [comment]
Well, actually this should already be correct. It checks if the `data` directory exists under `/usr/share/amiberry` before it decides to use that path as the `data` directory. Did you already have a directory created there earlier, perhaps? Maybe an empty one?

**Comment by m0ppers** [comment]
```
[mop@udoo-juergens amiberry]$ ls -al /usr/share/amiberry/
ls: cannot access '/usr/share/amiberry/': No such file or directory
[mop@udoo-juergens amiberry]$ XDG_DATA_HOME=/home/mop/.local/share/ XDG_DATA_DIRS=/tmp/ ./amiberry 
SDLTrueTypeFont::SDLTrueTypeFont. Couldn't open /usr/share/amiberry/data/AmigaTopaz.ttf: No such file or directory
Internal error; file src/osdep/gui/main_window.cpp, line 1050
Aborted (core dumped)
```

**Comment by giantclambake** [comment]
I was looking at this on & off over the last few days, but more about checking the cmake install directives, not so much this issue (which I cannot recreate in the stand-alone context ...if amiberry was copied to /usr/bin/ then I think it's possible for the wheels to fall off like this)....but otherwise, `./amiberry` from $build_dir (aka $PWD) works correctly....

...in fact, I think the only way to encounter this here, is if amiberry is outside $PWD ...or as you say, /usr/share/amiberry already exists (which it shouldn't really)...

When I checked against the LFS build, I did encounter problems, but mostly wrt AMIBERRY_HOME_DIR ...not the DATA dir, it was finding that correctly under /usr/share/amiberry/ if present. On the LFS build, the $ENV_VARS (that matter at build time =) are limited to;

declare -x PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"  //the path _/usr/lib/pkgconfig_ is searched by default
declare -x XDG_CONFIG_DIRS="/etc/xdg/"
declare -x XDG_DATA_DIRS="/usr/local/share:/usr/share/"
declare -x XDG_RUNTIME_DIR="/tmp/xdg-<username>"

..ergo, XDG_DATA_HOME is unset, and unless set otherwise, $PREFIX=/usr/local ... this is a tad unfortunate obviously, because amiberry searches /usr/share/amiberry for the DATA_DIR, not /usr/local/share/amiberry ;) Nothing saw this 'olde-skool' usage of /usr/local coming...and I suppose anyone wanting $PREFIX=/opt is in the same boat (there's likely a cmake -D<switch> to override this).... but this was OOTB so to speak....

....as that was the displayed behavior, copying amiberry into /usr/bin/ to put it in $PATH, and then copying the `data` directory to `/usr/share/amiberry/data` works as expected (sort of)...however, if you have  /usr/bin/amiberry and the data-path /usr/share/amiberry/data/ does not exist, will produce the error as per OP.... you'd need examine what the AUR package did, if it apparently fixed things...
.
.

..further, even when you have all that correct, if AMIBERRY_HOME_DIR & XDG_DATA_HOME are unset, and `~/.amiberry` does not exists, it defaults to $HOMEDIR{abr, cdroms, controllers, floppies, kickstarts, nvram, savestates, whdboot, conf,       harddrives  lha, plugins, screenshots}....when I was looking at it in Puppy, amiberry was expecting to find stuff in ~/.local/share/amiberry/{*}  ..this is apparently a default being used for $XDG_DATA_HOME in some distros...Bookworm/amd64 with XFCE4 install doesn't set this env_var. In any event, setting AMIBERRY_HOME_DIR to what you need, is an effective work-around.

Such as it is, this is mired in the answer to "what happens next?", in the case of a system-wide, multi-user install of amiberry, and any user starts amiberry for the first time...ie; the required dirs/files will not exist and need be created...

...FWIW, the build of fs-uae from source tarball handles this very well ; at make install time, it copies all the required resources into /usr/share/fs-uae -- at first-time-start it checks for $HOMEDIR/Documents and if exists, create the required FS-UAE(*) dirs/files there ~ if that path does not exist, create the required FS-UAE{*} dirs/files in $HOMEDIR. It also creates a ~/.config/fs-uae directory (the amiberry.conf might live here), and also a ~/.local/share/fs-uae directory (which is the default path for the fs-uae.logfile it seems)....

...everything looks analogous wrt the amiberry position...anything that really matters is 'hidden' inside .directories ; anything the user really needs to get to is in ~/FS-UAE or ~/Documents/FS-UAE  (here, I'm mentally inserting Amiberry as a directory name, with a capital A, as it naturally sorts it to the top of file-manager views...desktop or not... and besides, if 'fs-uae' went all capitals in these respects, I'm sure amiberry could have at least one 'deployed' capital letter =)....

....the wrinkle is, the whdboot directory ~ fs-uae doesn't have to deal with this. The whdboot/game-data and save-data have to be user writable, but the boot-data.zip/AmiQuit/WHDLoad files need to be copied into the newly created directory structure as well -- on top of that, these files may be updated upon any new future release, and thus something would need check these files, to see if newer ones (from the updated pkg) should be copied across... something like that... ;)

HTH

**Comment by giantclambake** [comment]
> XDG_DATA_HOME=/home/mop/.local/share/

Hmmm...as I mentioned, this Bookworm system doesn't employ the XDG_DATA_HOME env_var, and typically I build nested in homedir (~/Preview/amiberry/ and ~/Master/amiberry), but for this test I copied the Preview tree to ~/amiberry

First, set the variable...  `export XDG_DATA_HOME="/home/gcb/.local/share/"` follow on with `./amiberry`

![ex](https://imgur.com/Chs4LLwl.png)

...that'd be an interesting result, it seems $config_path and $retroarch_config paths aren't following the same rules, and it should be looking in `/home/gcb/.local/share/amiberry` for these files anyhow (yes, .local/share/amiberry/ exists), but it is getting the data-path correct... `data_dir=/home/gcb/amiberry/data/` ...even deleting the conf/amiberry.conf file and restarting ./amiberry had the same result ...and it still found $PWD/data no problems...Paths were weird...looks like the XDG_DATA_HOME handling needs improving a little....

...makes me think it's not honoring $PWD but I can't recreate it here (I can as explained above with amiberry in $PATH)

@m0ppers  -- are you using the make command, or the cmake route instead?

**Comment by m0ppers** [comment]
I investigated. 

I recently switched machines and didn't make a fresh clone but copied everything from my old disk and then rebuild on my new machine. The old machine had amiberry installed.

the reason this happened was that the conf/amiberry.conf was modified on my old computer and datadir was set to /usr/share/bla

at startup amiberry seems to read that and overwrites the default assumptions. initially (the commited version) it doesn't contain a data_dir. but as soon as amiberry starts it will write a data_dir there if not present (git status shows modifications).

if I make a fresh clone, compile and start up for the first time the data dir in the config file will point to the source directory (just as I would expect).
If I startup for the first time in my source directory AND I have installed amiberry on my system the file will contain data_dir=/usr/share/bla

I think if amiberry wouldn't overwrite the config file upon startup everything would be fine. As I said: super minor issue as the workaround is trivial and this is likely a case that is not relevant for 99% of the users :joy:

**Comment by m0ppers** [comment]
@giantclambake I am using the Makefile. Not CMake. I don't think this has anything to do with the build process.

**Comment by m0ppers** [comment]
in case my comment caused more confusion than it was helpful :joy: :

```
[mop@udoo-juergens amiberry2]$ git reset --hard
[mop@udoo-juergens amiberry2]$ cat conf/amiberry.conf | grep data
[mop@udoo-juergens amiberry2]$ sudo pacman -R amiberry # remove system amiberry
[mop@udoo-juergens amiberry2]$ ./amiberry 
[mop@udoo-juergens amiberry2]$ cat conf/amiberry.conf | grep data
floppy_sounds_dir=/home/mop/projects/amiberry2/data/floppy_sounds/
data_dir=/home/mop/projects/amiberry2/data/
[mop@udoo-juergens amiberry2]$ MAKEFLAGS=-j8 yay -S amiberry # install amiberry from AUR
[...]
[mop@udoo-juergens amiberry2]$ git reset --hard
[mop@udoo-juergens amiberry2]$ ./amiberry 
[mop@udoo-juergens amiberry2]$ cat conf/amiberry.conf | grep data
floppy_sounds_dir=/usr/share/amiberry/data/floppy_sounds/
data_dir=/usr/share/amiberry/data/
[mop@udoo-juergens amiberry2]$ git reset --hard
[mop@udoo-juergens amiberry2]$ sudo pacman -R amiberry # remove system amiberry again
[mop@udoo-juergens amiberry2]$ ./amiberry  # now comes this bug
SDLTrueTypeFont::SDLTrueTypeFont. Couldn't open /usr/share/amiberry/data/AmigaTopaz.ttf: No such file or directory
Internal error; file src/osdep/gui/main_window.cpp, line 1050
Aborted (core dumped)
```

**Comment by midwan** [comment]
@m0ppers 
Ah, that explains it then.
Yes, if the file exists, it will override any defaults that are guessed on startup - that is by design.
