### ISSUE TITLE
Resume button disables mouse and keyboard

### ISSUE THREAD

**Issue by Akallabeth13666** [BlitterStudio/amiberry#1491]
**Describe the bug**
When emulating anything, after I click F12 and enter configuration, do what I need, then click on 'Resume' button mouse and keyboard stops working

**To Reproduce**
As above

**Expected behavior**
Mouse and keyboard to work

**Comment by midwan** [comment]
More details are needed.
This is not standard behavior, and I cannot recreate it anywhere currently.

Which environment are you using?
Which linux distro?
Is it windowed or running from the console?
Which Amiberry version?

Generally, we need detailed steps to recreate the problem, in order to do something about it. :)
