### ISSUE TITLE
*.vbi video roms now visible, but not selectable

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1515]
These video rom files are now visible after https://github.com/BlitterStudio/amiberry/commit/85044a8690104540e95f7ed622312333570053dd

However....

*selecting a *.vbi file is not refreshed/updated in the associated GUI textbox

*likewise. the selected *.vbi file is not saved to the currently loaded config.uae file

As we're none too sure where 'firm ground' is here, I was looking at...(note: CL_TYPE_AVGA2 = Cirrus Logic GD5402)

```
src/pcem/vid_cl5429.cpp:         return cl_init(CL_TYPE_AVGA2, "avga2vram.vbi", -1, 0);
src/pcem/vid_cl5429.cpp:         return cl_init(CL_TYPE_GD5428, "Machspeed_VGA_GUI_2100_VLB.vbi", -1, 0);
src/pcem/vid_cl5429.cpp:         return cl_init(CL_TYPE_GD5429, "5429.vbi", -1, 0);
src/pcem/vid_cl5429.cpp:         return rom_present("avga2vram.vbi");
src/pcem/vid_cl5429.cpp:         return rom_present("Machspeed_VGA_GUI_2100_VLB.vbi");
src/pcem/vid_cl5429.cpp:         return rom_present("5429.vbi");
```

Query: does this infer the .vbi files are to be auto-detected by cl_init(type)?

TIA

**Comment by midwan** [comment]
I'm not 100% sure how it's supposed to work here, and if this is a bug in WinUAE as well. The rom is checked against the internal list of recognized ones, and if there's no match, it's ignored. Apparently, these VGA board roms are not included there.

**Comment by midwan** [comment]
If you look at the code, `cl_init()` will call `rom_init()` if a vbi file was specified, but `rom_init()` is hardcoded to always return 0.

So it looks like those files are never really used.
The git history shows that Toni added/changed these, but I don't know if this was by design or the reasoning behind it. 

Either way, it doesn't look like an issue in Amiberry specifically. If it should be changed, I believe it would be best done upstream in WinUAE.

I will revert the changes to show the `.vbi` files as they don't make any sense under the circumstances.

**Comment by giantclambake** [comment]
Agreed ...essentially it was why I broke this out into it's own ticket ; to me at least, it didn't 'look right' to be exposing the .vbi files, and you're right -- if something's wrong here, it's just as 'wrong' upstream (seeing as amiberry is following the example of what WinUAE is doing)...

...on the positive side, the MDA/CGA video of the A2386SX emulation seems to work fine, so there's no real loss here.

I'll leave it to you to close or upmark this ticket...it's likely a niche usage case (but you know what my luck's like, I tend to find weird things ;)
