### ISSUE TITLE
GPIO green LED strange behavior

### ISSUE THREAD

**Issue by TomBonk** [BlitterStudio/amiberry#1533]
The green LED (GPIO 24) turns off when any application that generates sound (or opens a sound device.) is started.

It doesn't matter if it is a system application (e.g. AmigaAMP, HippoPlayer) or a WHDLoad game.

The green LED turns on immediately when the audio application is closed or WHDLoad is closed.

Other LEDs are working properly.

- OS: DietPi with Amiberry 5.7.5 (compiled from sources)
- Raspberry Pi 5 4GB.

**Comment by midwan** [comment]
The Green LED represents the power LED state. Could it be that this is related to the Amiga-side Filter?
On real Amigas, the filter state would turn the Power (Green) Led to full or half brightness, but I'm not sure we can have half-brightness on the GPIO (the library indicates an ON/OFF state is possible only).

**Comment by TomBonk** [comment]
On my real Amiga 500, the green led is half bright by default. It lights up fully for a while when starting WHDLoad and then dims again after a while.

Music players don't affect the brightness of the LED at all like they do on Amiberry.

I'm not sure if we definitely need the real power LED behavior in emulation. You could just hook up the green LED to the power supply permanently.

I did for the test something like in the picture. Two resistors (680 ohm and 150 ohm) to achieve different brightnesses. In addition, a small diode in series.

I can now brighten the LED by turning the GPIO on or off.

Someone smarter than me would have to check whether such a connection of two GPIOs is safe for the raspberry in the  long term. For now, it works for me.

![IMG_20241214_192832992](https://github.com/user-attachments/assets/5b971ff6-477e-4748-b350-42c18d09f144)

**Comment by midwan** [comment]
Thanks for the above.
The green LED is currently hooked to the Power LED status, with an ON/OFF boolean state.

**Comment by giantclambake** [comment]
> Someone smarter than me would have to check whether such a connection of two GPIOs is safe for the raspberry in the long term. For now, it works for me.

@TomBonk 

I don't know the actual specs of the LED you used, but I can ball-park the calculations.

The way you have it wired, the 150R resistor is going to present around 8mA of current to sink at the GPIO pin.

The RPi GPIO port is technically limited to 3~5mA per pin, so you should change the 150R  resistor to 220R to be safe.

Apart from that, this circuit won't damage the RPi in any way ; just change that resistor to put it closer to spec  ;)

HTH

**Comment by giantclambake** [comment]
> On my real Amiga 500, the green led is half bright by default. It lights up fully for a while when starting WHDLoad and then dims again after a while.
> 
> Music players don't affect the brightness of the LED at all like they do on Amiberry.
> 
> I'm not sure if we definitely need the real power LED behavior in emulation. You could just hook up the green LED to the power supply permanently.

That actually comes across as a fault wrt your A500 ...or... something wrong with the keyboard controller (the A500 was fitted with a couple of different keyboard assemblies, some which controlled the LEDs directly rather than using the drivers on the mainboard). I've not tested this, but, if amiberry GPIO is altering the brightness of the 'Power' LED during music module playback, this would be 'correct' emulation ~ it's signifying audio filter ON/OFF events, as encoded into the (tracker) music module(s)..... my real A500 does exactly the same thing ;)

![ex](https://imgur.com/WLJj74z.png)

...going a little OT and trying to be helpful.... when the A500 powers up, current flows through R507 to the Power (status) LED, and Q502 is held OFF by the pull-up voltage applied to it's base via R505 -- this is the 'dimmed' LED state.

The active low signal **_LED** is controlled by the ODD_CIA (8520, U7), and this signal also switches the audio filter ON/OFF  --- when this signal is active, as in providing a path to ground, the LED driver transistor Q502 turns on, which shunts R507 and thus providing increased current to the LED -- this is the 'bright' LED state....and the same time, the audio filter circuit is enabled, whenever **_LED** goes active low....

...OTOH if I've misread, and amiberry is _not_ doing this...it should  ;)

**Comment by TomBonk** [comment]
So Amiberry is doing everything correctly. 
There is just a piece of the circuit missing. Recreating it should not be a problem.

Thank you all for your help.

**Comment by midwan** [comment]
Closing this then
