### ISSUE TITLE
GUI: JIT-option not available for 68020 directly

### ISSUE THREAD

**Issue by AndyFx12** [BlitterStudio/amiberry#1560]
**Describe the bug**
GUI don't allow select JIT-compiler for 68020 CPU - but after switching to 68030 and back, it is available.

**To Reproduce**

1. Go to CPU and FPU and select 68020 -> no JIT available

2. Click on 68030 

3. Click on 68020

4. -> JIT is available

**Expected behavior**
If 68020 emulation supports JIT, it should be always selectable.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/78f8b3a1-3436-42da-a60c-13ef40856287)
![grafik](https://github.com/user-attachments/assets/41bc7a47-c7d5-4a88-b65b-3728b723dfcb)
![grafik](https://github.com/user-attachments/assets/a6c12bf4-0727-4ee5-967b-1fdb2713ad08)

**Desktop (please complete the following information):**

- OS: Linux Mint with Cinnamon

- Version 22

Love Amiberry? Please consider supporting it:
👉  https://ko-fi.com/midwan

**Comment by giantclambake** [comment]
Confirmed, something odd here.... another scenario...

- Go to CPU and FPU panel
- Unselect 24bit addressing
- Select 68020 // JIT is available..

**Comment by midwan** [comment]
You can not enable JIT with 24-bit addressing selected. That's logic coming straight from upstream WinUAE, in fact.

**Comment by AndyFx12** [comment]
OK - thanks for your explanation.

**Comment by giantclambake** [comment]
It's actually a machination of the GUI  (WinUAE is doing the same thing)...

....ideally, the 24-bit addressing checkbox should be re-enabled, when changing from 68030 to 68020 (like what happens when you change from 68030 to 68000/68010) ~ it gives the impression something's gone awry ...ie; if the user never touched 68020 24-bit addressing, it should not change as a consequence of other operations...

...in a perfect world, it should behave like the 68030 => 68000/68010 case.... but meh...  8^)

**Comment by midwan** [comment]
Yes, it's a sanity check done by the GUI, but not only: it's also done when loading a config, to ensure that the settings are correct.
