### ISSUE TITLE
Amiberry opens gui when launching whdboot game

### ISSUE THREAD

**Issue by AnalogHero** [BlitterStudio/amiberry#988]
Hi,

Since i updated to amiberry 5.2 from the retropie setup script, i noticed that when i launch a game it always opens the gui. If i click on reset, the game launches normal.

Things ive tried so far:

-Removing every remnance of amiberry and reinstalling

-launching amiberry from command line (with --autoboot)

-creating a default.uae (although i know not needed) with show gui on start off

Dont know what caused this behavior. Only thing that maybe worth mentioning is that i updated amiberry several times with the latest (dev) build.

Thanks for any advice

**Comment by midwan** [comment]
I can't recreate this anywhere, so far.
It must be something specific to your environment, but I'm not sure what at this point. Have you tried wit h a fresh image of RetroPie, to see if it works as expected there for you?

**Comment by AnalogHero** [comment]
Hi. 
I can recreate it. It seems he problem occurs after i configured my 8bitdo controller. Without it everything is fine.
Exact model of the controller is 8bitDo NES30 Pro.

**Comment by midwan** [comment]
@AnalogHero 
Could it be that for some reason the hotkey to open the GUI is seen as pressed on startup?
Could you post your controller configuration file here?

**Comment by AnalogHero** [comment]
Here is my retroarch joypad config file.
If you need another file ill will send it to you.
[8Bitdo NES30 Pro.zip](https://github.com/BlitterStudio/amiberry/files/9021272/8Bitdo.NES30.Pro.zip)

**Comment by nemo93** [comment]
@AnalogHero please confirm your issue remains when you connect your 8bitDo via USB? I do have Xbox One controller over bluetooth and can't reproduce either.

**Comment by AnalogHero** [comment]
@nemo93 
Tested it. I removed the paired bluetooth device and connected the pad with usb. Now it works perfect.

Strange bug.

Ps. After i paired it again, it has the same behavior as before.

**Comment by nemo93** [comment]
@AnalogHero thanks for confirming. You're not alone in that case I'm afraid. I'd recommend we close that ticket off to continue on [Retropie's forum](https://retropie.org.uk/forum/topic/32648/amiberry-5-1-controller-mapping-problem-since-upgading-from-3-x/28). Your issue could be related to a rather old library bundled with Retropie (not confirmed yet). 

This is why I have to insist on people using Retropie as distro to first raise ticket on the forum and only if no answer/fix found to crack a ticket open on that Github.
